### PR TITLE
Add disabled attribute.

### PR DESCRIPTION
**Pull request by vivekimsit**
The `index.html` is just for demo purpose and will be removed after approval.

Changelog:
1. Add `disabled` attribute to disable elements on boolean conditions.
2. Add pre-checks and throw error if element cannot have the above attribute.

Issue:

At present the `disabled` attribute is applied to all the `option` attribute of the `select` element and hence throws err.

### CODE REVIEW

**Comment by solkimicreb** [comment]
Hi!

I have to work now, but I will check it in depth soon.

Thx for the PR!

**Comment by vivekimsit** [comment]
@solkimicreb if you get time please have a look at it.

**Comment by solkimicreb** [comment]
@vivekimsit 
Sorry, for being so slow ): I checked it, looks great! The next version will be alpha 3.0.0 and it will include your PR (:

I am not sure about what Git work flow to use, as this is my first community project. Are you experienced with Git, any suggestions?

P.S.: I would like to add a `contributors.md` with v3.0 with your name/home page, etc. What info and links would you like to be displayed there? (alternatively you can make a PR for it, if it is easier for you)

**Comment by solkimicreb** [comment]
I did not figure out anything for the repeated utility functions issue yet. Maybe we could move them into utility files in the future.

**Comment by vivekimsit** [comment]
@solkimicreb no issue so by the time I will look into validation stuff now. About contribution sending PR sounds reasonable. Thanks :+1:

**Pull request closed without merging**
